#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  # colorscheme = "gruvbox"
  # background = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  colorscheme="molokai_dark"
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_display_mode = true
  plugin_bundle_dir="~/.config/vimfiles"
  enable_neomake=false
  enable_ale=true
  lint_on_the_fly=true
  bootstrap_after="myvim#after"
 

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 20

[[layers]]
  name='colorscheme'

[[layers]]
  name='tools'

[[layers]]
  name='fzf'

[[layers]]
  name='unite'

[[layers]]
  name='tags'

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"
  format-on-save=1

[[layers]]
  name = "lang#ocaml"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#sh"

[[layers]]
  name='lsp'

[[layers]]
  name='denite'

[[layers]]
  name='checkers'

[[layers]]
  name = "lang#markdown"

[[layers]]
  name='lsp'

[[layers]]
  name='denite'

[[layers]]
  name='checkers'

[[custom_plugins]]
  name='rafi/awesome-vim-colorschemes'
  merged= false

[[custom_plugins]]
  name='ujihisa/neco-look'
  merged= false

[[custom_plugins]]
  name='ujihisa/unite-colorscheme'
  merged= false

[[custom_plugins]]
  name='flazz/vim-colorschemes'
  merged= false

